# Generated by Django 5.0.4 on 2024-05-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='genero',
        ),
    ]
