# Generated by Django 5.0.4 on 2024-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_genero_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=10),
        ),
    ]
